### ISSUE TITLE
Uncollapsed sections

### ISSUE THREAD

**Issue by baspinarenes** [Trendyol/ios-guidelines#21]
Hey. I've had a look at the documentation, good work. But just a quick browse and when I want to search for swift keywords, collapsed sections won't let me. Maybe the codes can be uncollapsed. I just wanted to give a suggestion 🧡

**Comment by batuhansk** [comment]
Hey @baspinarenes,

Thanks for your suggestion. There is an ongoing initiative for code style guide, and we will definitely consider this.
