### ISSUE TITLE
if let - guard let shorthand misusage

### ISSUE THREAD

**Issue by wynioux** [Trendyol/ios-guidelines#74]
**A short summary of issue:**
In our guideline there is a [misuse](https://github.com/Trendyol/ios-guidelines/blob/master/code_style_guideline/code_style_guideline.md#golden-path) of optional binding using `if let foo = foo { ... }` and `guard let foo = foo else { ... }`.

**Reasoning and motivation:**
After release of Swift 5.7 we can use new `if let foo { ... }` and `guard let foo else { ... }` shorthand syntax as our guideline mentioned [here](https://github.com/Trendyol/ios-guidelines/blob/master/code_style_guideline/code_style_guideline.md#omit-the-right-hand-side-of-the-expression).

**Sources:**
[swift-evolution](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0345-if-let-shorthand.md#if-let-shorthand-for-shadowing-an-existing-optional-variable)

**Comment by eminozkalaycioglu1** [comment]
Yes, i agree. Thanks for your attention :)
We'll fix it with this [MR](https://github.com/Trendyol/ios-guidelines/pull/77).
