### ISSUE TITLE
Need for text update for new xcode versions

### ISSUE THREAD

**Issue by mavideniz** [Trendyol/ios-guidelines#75]
With the update of Xcode, the word "settings" started to be used instead of "preferences". In this context, updating the following places will help the person following the guide.

Old: Go to  Xcode > Preferences > Text Editing > While editing
New: Go to  Xcode > **Settings** > Text Editing > **Editing**

**Comment by tolgayildirim** [comment]
Thanks for your support. We've fixed it in this [PR](https://github.com/Trendyol/ios-guidelines/pull/80).
