### ISSUE TITLE
Access Control Examples

### ISSUE THREAD

**Issue by devmehmetates** [Trendyol/ios-guidelines#78]
### A short summary of issue:
In our guideline there is a [Access control](https://github.com/Trendyol/ios-guidelines/blob/master/code_style_guideline/code_style_guideline.md#access-control).

Here, preferred and not preferred values ​​appear to be the same.

### Reasoning and motivation:

When the article is examined, the fact that the sample values ​​are the same strengthens the understanding of the article.

The substance can be strengthened by diversifying the examples.

**Comment by tolgayildirim** [comment]
Thanks for your support. We've fixed it in this [PR](https://github.com/Trendyol/ios-guidelines/pull/80).
